/* Datoon, Philip Bryan B.
 * 131311399
 * Cluster 3 - Project 2
 */

package Project02;

import java.awt.Font;
import javax.swing.JOptionPane;

public class JFontSelector extends javax.swing.JFrame {

    private int fontSize;
    private Font TimesNewRoman;
    private Font CenturyGothic;
    private Font CourierNew;
    private Font Impact;
    private Font OldEnglish;
    
    public JFontSelector() {
        initComponents();
        
        // gets font size value
        this.fontSize = lbl_display.getFont().getSize();
        
        // creates Font instance
        this.TimesNewRoman = new Font("Times New Roman", 0, getFontSize());
        this.CenturyGothic = new Font("Century Gothic", 0, getFontSize());
        this.CourierNew = new Font("Courier New", 0, getFontSize());
        this.Impact = new Font("Impact", 0, getFontSize());
        this.OldEnglish = new Font("Old English Text MT", 0, getFontSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_fontFamily = new javax.swing.JPanel();
        btn_TimesNewRoman = new javax.swing.JButton();
        btn_CenturyGothic = new javax.swing.JButton();
        btn_CourierNew = new javax.swing.JButton();
        btn_Impact = new javax.swing.JButton();
        btn_OldEnglish = new javax.swing.JButton();
        panel_FontSize = new javax.swing.JPanel();
        btn_smaller = new javax.swing.JButton();
        btn_larger = new javax.swing.JButton();
        lbl_fontSize = new javax.swing.JLabel();
        lbl_display = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_fontFamily.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose font style"));

        btn_TimesNewRoman.setText("Times New Roman");
        btn_TimesNewRoman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimesNewRomanActionPerformed(evt);
            }
        });

        btn_CenturyGothic.setText("Century Gothic");
        btn_CenturyGothic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CenturyGothicActionPerformed(evt);
            }
        });

        btn_CourierNew.setText("Courier New");
        btn_CourierNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CourierNewActionPerformed(evt);
            }
        });

        btn_Impact.setText("Impact");
        btn_Impact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ImpactActionPerformed(evt);
            }
        });

        btn_OldEnglish.setText("Old English Text");
        btn_OldEnglish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OldEnglishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_fontFamilyLayout = new javax.swing.GroupLayout(panel_fontFamily);
        panel_fontFamily.setLayout(panel_fontFamilyLayout);
        panel_fontFamilyLayout.setHorizontalGroup(
            panel_fontFamilyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fontFamilyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_fontFamilyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_CenturyGothic, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_CourierNew, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Impact, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_OldEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimesNewRoman, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_fontFamilyLayout.setVerticalGroup(
            panel_fontFamilyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_fontFamilyLayout.createSequentialGroup()
                .addComponent(btn_TimesNewRoman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CenturyGothic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CourierNew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Impact)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_OldEnglish))
        );

        panel_FontSize.setBorder(javax.swing.BorderFactory.createTitledBorder("Choose font size"));

        btn_smaller.setText("Smaller --");
        btn_smaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_smallerActionPerformed(evt);
            }
        });

        btn_larger.setText("Larger ++");
        btn_larger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_largerActionPerformed(evt);
            }
        });

        lbl_fontSize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_fontSize.setText("Current font size: " + lbl_display.getFont().getSize() + "pt");

        javax.swing.GroupLayout panel_FontSizeLayout = new javax.swing.GroupLayout(panel_FontSize);
        panel_FontSize.setLayout(panel_FontSizeLayout);
        panel_FontSizeLayout.setHorizontalGroup(
            panel_FontSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FontSizeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_FontSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_smaller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_larger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_fontSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_FontSizeLayout.setVerticalGroup(
            panel_FontSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_FontSizeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_smaller)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_larger)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_fontSize)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_display.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbl_display.setText("The quick brown fox jumps over the lazy dog.");
        lbl_display.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lbl_display.setBorder(javax.swing.BorderFactory.createTitledBorder("Display"));

        btn_reset.setText("Reset display");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_fontFamily, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_FontSize, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_display, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_fontFamily, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_FontSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_reset)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TimesNewRomanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimesNewRomanActionPerformed
        lbl_display.setFont(TimesNewRoman);
    }//GEN-LAST:event_btn_TimesNewRomanActionPerformed

    private void btn_CenturyGothicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CenturyGothicActionPerformed
        lbl_display.setFont(CenturyGothic);
    }//GEN-LAST:event_btn_CenturyGothicActionPerformed

    private void btn_CourierNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CourierNewActionPerformed
        lbl_display.setFont(CourierNew);
    }//GEN-LAST:event_btn_CourierNewActionPerformed

    private void btn_ImpactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ImpactActionPerformed
        lbl_display.setFont(Impact);
    }//GEN-LAST:event_btn_ImpactActionPerformed

    private void btn_OldEnglishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OldEnglishActionPerformed
        lbl_display.setFont(OldEnglish);
    }//GEN-LAST:event_btn_OldEnglishActionPerformed

    private void btn_smallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_smallerActionPerformed
        if (getFontSize() > 0) {
            setFontSize(fontSize - 2);
            
            lbl_display.setFont(new Font(lbl_display.getFont().getFamily(),
                0, getFontSize()));
        } else {
            JOptionPane.showMessageDialog(null, "Too small!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        displayCurrentFontSize();
    }//GEN-LAST:event_btn_smallerActionPerformed

    private void btn_largerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_largerActionPerformed
        if (getFontSize() < 40) {
            setFontSize(fontSize + 2);
            
            lbl_display.setFont(new Font(lbl_display.getFont().getFamily(),
                0, getFontSize()));
        } else {
            JOptionPane.showMessageDialog(null, "Too large!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        displayCurrentFontSize();
    }//GEN-LAST:event_btn_largerActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        setFontSize(12);
        lbl_display.setFont(new Font("Tahoma", 0, getFontSize()));
        displayCurrentFontSize();
    }//GEN-LAST:event_btn_resetActionPerformed

    private int getFontSize() {
        return this.fontSize;
    }
    
    private void setFontSize(int fontSize) {
        this.fontSize = fontSize;
    }
    
    private void displayCurrentFontSize() {
        lbl_fontSize.setText("Current font size: " + getFontSize() + "pt");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFontSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFontSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFontSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFontSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFontSelector().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CenturyGothic;
    private javax.swing.JButton btn_CourierNew;
    private javax.swing.JButton btn_Impact;
    private javax.swing.JButton btn_OldEnglish;
    private javax.swing.JButton btn_TimesNewRoman;
    private javax.swing.JButton btn_larger;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_smaller;
    private javax.swing.JLabel lbl_display;
    private javax.swing.JLabel lbl_fontSize;
    private javax.swing.JPanel panel_FontSize;
    private javax.swing.JPanel panel_fontFamily;
    // End of variables declaration//GEN-END:variables
}
